open-monitor-center/cachecloud/cachecloud-open-web/src/main/java/com/sohu/cache/entity/AppDesc.java
package com.sohu.cache.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;

import com.alibaba.fastjson.JSONObject;
import com.sohu.cache.constant.AppDescEnum;
import com.sohu.cache.constant.AppDescEnum.AppImportantLevel;
import com.sohu.cache.constant.AppStatusEnum;
import com.sohu.cache.util.ConstUtils;

/**
 * 应用的信息，包括分片、类型以及各分片的ip
 * <p/>
 * User: lingguo
 * Date: 14-5-29
 * Time: 下午9:42
 */
public class AppDesc implements Serializable {
    private static final long serialVersionUID = -3507970915810652761L;

    /**
     * 应用id
     */
    private long appId;
    
    /**
     * 应用秘钥
     */
    private String appKey;

    /**
     * 应用名称
     */
    private String name;

    /**
     * 用户id
     */
    private long userId;

    /**
     * 应用状态, 0未分配，1是申请了未审批，2是审批并发布, 3应用下线
     */
    private int status;

    /**
     * 应用描述
     */
    private String intro;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 申请通过的时间
     */
    private Date passedTime;

    /**
     * 类型
     */
    private int type;

    /**
     * 类型描述
     */
    private String typeDesc;

    /**
     * 负责人
     */
    private String officer;

    /**
     * 版本号
     */
    private int verId;

    /**
     * 是否测试：1是0否
     */
    private int isTest;

    /**
     * 是否有后端数据源: 1是0否
     */
    private int hasBackStore;

    /**
     * 是否需要持久化: 1是0否
     */
    private int needPersistence;

    /**
     * 预估qps
     */
    private int forecaseQps;

    /**
     * 是否需要热备: 1是0否
     */
    private int needHotBackUp;

    /**
     * 预估条目数
     */
    private int forecastObjNum;

    /**
     * 内存报警阀值
     */
    private int memAlertValue;
    
    /**
     * 客户端连接数报警阀值
     */
    private int clientConnAlertValue;
    
    /**
     * 客户端机器机房
     */
    private String clientMachineRoom;
    
    /**
     * redis密码
     */
    private String password;
    
    /**
     * 重要度，默认重要
     */
    private int importantLevel = AppImportantLevel.IMPORTANT.getValue();

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getPassedTime() {
        return passedTime;
    }

    public void setPassedTime(Date passedTime) {
        this.passedTime = passedTime;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getOfficer() {
        return officer;
    }

    public void setOfficer(String officer) {
        this.officer = officer;
    }

    public int getVerId() {
        return verId;
    }

    public void setVerId(int verId) {
        this.verId = verId;
    }

    public int getIsTest() {
        return isTest;
    }

    public void setIsTest(int isTest) {
        this.isTest = isTest;
    }

    public int getHasBackStore() {
        return hasBackStore;
    }

    public void setHasBackStore(int hasBackStore) {
        this.hasBackStore = hasBackStore;
    }

    public int getNeedPersistence() {
        return needPersistence;
    }

    public void setNeedPersistence(int needPersistence) {
        this.needPersistence = needPersistence;
    }


    public int getForecaseQps() {
        return forecaseQps;
    }

    public void setForecaseQps(int forecaseQps) {
        this.forecaseQps = forecaseQps;
    }

    public int getNeedHotBackUp() {
        return needHotBackUp;
    }

    public void setNeedHotBackUp(int needHotBackUp) {
        this.needHotBackUp = needHotBackUp;
    }

    public int getForecastObjNum() {
        return forecastObjNum;
    }

    public void setForecastObjNum(int forecastObjNum) {
        this.forecastObjNum = forecastObjNum;
    }

    public int getMemAlertValue() {
        return memAlertValue;
    }

    public void setMemAlertValue(int memAlertValue) {
        this.memAlertValue = memAlertValue;
    }

    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    public String getClientMachineRoom() {
        return clientMachineRoom;
    }

    public void setClientMachineRoom(String clientMachineRoom) {
        this.clientMachineRoom = clientMachineRoom;
    }
    
    public String getAppKey() {
        return appKey;
    }

    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    public int getClientConnAlertValue() {
        return clientConnAlertValue;
    }

    public void setClientConnAlertValue(int clientConnAlertValue) {
        this.clientConnAlertValue = clientConnAlertValue;
    }
    
    public int getImportantLevel() {
        return importantLevel;
    }

    public void setImportantLevel(int importantLevel) {
        this.importantLevel = importantLevel;
    }
    
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 应用运行天数
     */
    public int getAppRunDays() {
        if (createTime == null) {
            return -1;
        }
        Date now = new Date();
        long diff = now.getTime() - createTime.getTime();
        return (int) (diff / TimeUnit.DAYS.toMillis(1));
    }

    public String getTypeDesc() {
        if (type <= 0) {
            return "";
        } else if (type == ConstUtils.CACHE_TYPE_REDIS_CLUSTER) {
            return "redis-cluster";
        } else if (type == ConstUtils.CACHE_REDIS_SENTINEL) {
            return "redis-sentinel";
        } else if (type == ConstUtils.CACHE_REDIS_STANDALONE) {
            return "redis-standalone";
        }
        return "";
    }
    
    public String getCreateTimeFormat(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if(createTime != null){
            return sdf.format(createTime);
        }
        return "";
    }


    @Override
    public String toString() {
        return JSONObject.toJSONString(this);
    }

    public String getStatusDesc() {
        AppStatusEnum appStatusEnum = AppStatusEnum.getByStatus(status);
        if (appStatusEnum != null) {
            return appStatusEnum.getInfo();
        }
        return "";
    }


    /**
     * 是否下线
     * @return
     */
    public boolean isOffline() {
        return status == AppStatusEnum.STATUS_OFFLINE.getStatus();
    }

    /**
     * 是否是测试
     * @return
     */
    public boolean isTest() {
        return isTest == AppDescEnum.AppTest.IS_TEST.getValue();
    }

    /**
     * 非常重要
     * @return
     */
    public boolean isVeryImportant() {
        return importantLevel == AppDescEnum.AppImportantLevel.VERY_IMPORTANT.getValue();
    }
    
    /**
     * 超级重要
     * @return
     */
    public boolean isSuperImportant() {
        return importantLevel == AppDescEnum.AppImportantLevel.SUPER_IMPORTANT.getValue();
    }

}

open-monitor-center/cachecloud/cachecloud-open-web/src/main/java/com/sohu/cache/entity/AppStats.java
package com.sohu.cache.entity;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.math.NumberUtils;

/**
 * Created by yijunzhang on 14-6-9.
 */
public class AppStats {

    /**
     * 应用id
     */
    private long appId;

    /**
     * 收集时间:格式yyyyMMddHHmm/yyyyMMdd/yyyyMMddHH
     */
    private long collectTime;

    /**
     * 命中数量
     */
    private long hits;

    /**
     * 未命中数量
     */
    private long misses;

    /**
     * 命令执行次数
     */
    private long commandCount;

    /**
     * 内存占用
     */
    private long usedMemory;

    /**
     * 过期key数量
     */
    private long expiredKeys;

    /**
     * 驱逐key数量
     */
    private long evictedKeys;

    /**
     * 网络输入字节
     */
    private long netInputByte;

    /**
     * 网络输出字节
     */
    private long netOutputByte;

    /**
     * 客户端连接数
     */
    private int connectedClients;

    /**
     * 存储对象数
     */
    private long objectSize;

    /**
     * 累加的实例数
     */
    private int accumulation;

    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 命令统计集合
     */
    private List<AppCommandStats> commandStatsList;

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public long getCollectTime() {
        return collectTime;
    }

    public void setCollectTime(long collectTime) {
        this.collectTime = collectTime;
    }

    public long getHits() {
        return hits;
    }
    
    /**
     * 命中率
     * @return
     */
    public long getHitPercent() {
        long total = hits + misses;
        if (total == 0) {
            return 0;
        } else {
            NumberFormat formatter = new DecimalFormat("0");
            return NumberUtils.toLong(formatter.format(hits * 100.0 / total));
        }
    }
    
    public void setHits(long hits) {
        this.hits = hits;
    }

    public long getMisses() {
        return misses;
    }

    public void setMisses(long misses) {
        this.misses = misses;
    }

    public long getUsedMemory() {
        return usedMemory;
    }

    public void setUsedMemory(long usedMemory) {
        this.usedMemory = usedMemory;
    }

    public long getExpiredKeys() {
        return expiredKeys;
    }

    public void setExpiredKeys(long expiredKeys) {
        this.expiredKeys = expiredKeys;
    }

    public long getEvictedKeys() {
        return evictedKeys;
    }

    public void setEvictedKeys(long evictedKeys) {
        this.evictedKeys = evictedKeys;
    }

    public int getConnectedClients() {
        return connectedClients;
    }

    public void setConnectedClients(int connectedClients) {
        this.connectedClients = connectedClients;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "AppStats{" +
                "appId=" + appId +
                ", collectTime=" + collectTime +
                ", hits=" + hits +
                ", misses=" + misses +
                ", usedMemory=" + usedMemory +
                ", expiredKeys=" + expiredKeys +
                ", evictedKeys=" + evictedKeys +
                ", connectedClients=" + connectedClients +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                ", objectSize=" + objectSize +
                ", accumulation=" + accumulation +
                '}';
    }

    public long getCommandCount() {
        return commandCount;
    }

    public void setCommandCount(long commandCount) {
        this.commandCount = commandCount;
    }

    public void setObjectSize(long objectSize) {
        this.objectSize = objectSize;
    }

    public long getObjectSize() {
        return objectSize;
    }

    public int getAccumulation() {
        return accumulation;
    }

    public void setAccumulation(int accumulation) {
        this.accumulation = accumulation;
    }

    public List<AppCommandStats> getCommandStatsList() {
        return commandStatsList;
    }

    public void setCommandStatsList(List<AppCommandStats> commandStatsList) {
        this.commandStatsList = commandStatsList;
    }

    public long getNetInputByte() {
        return netInputByte;
    }

    public void setNetInputByte(long netInputByte) {
        this.netInputByte = netInputByte;
    }

    public long getNetOutputByte() {
        return netOutputByte;
    }

    public void setNetOutputByte(long netOutputByte) {
        this.netOutputByte = netOutputByte;
    }
}

open-monitor-center/cachecloud/cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appCommand.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="row">
    <div id="console" class="console"></div>
    <script type="text/javascript">
        $(document).ready(function () {
            var console = $('#console');
            var controller = console.console({
                promptLabel: 'appId:${appId}> ',
                commandValidate: function (line) {
                    if (line == "") return false;
                    else return true;
                },
                commandHandle: function (line,report) {
                    $.ajax({
                        url: "/admin/app/commandExecute.json",
                        data: {appId: $('#appId').val(), command: line},
                        dataType: "json",
                        success: function (result) {
                            report([
                                {msg: result.result,
                                    className: "jquery-console-message-value"}
                            ]);
                        }
                    });
                },
                autofocus: true,
                animateScroll: true,
                promptHistory: true
            });
        });
    </script>
    <center><h4><font color='red'>注意：非测试应用只可以执行只读命令，如有需要清理数据请联系管理员！</font></h4></center>

    <input type="hidden" id="appId" value="${appId}">

</div>

open-monitor-center/cachecloud/cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appDemo.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp" %>
<div class="row">
    <br/>
    
    Maven Dependency：
    <div id="dependency" class="highlight">
        <pre class="prettyprint">
            <c:forEach var="line" items="${dependency}">
            ${line}<br/>
            </c:forEach>
        </pre>
    </div>

	Demo Code：
    <div id="code" class="highlight">
        <pre class="prettyprint">
        <c:forEach var="line" items="${code}">
            ${line}<br/>
        </c:forEach>
        </pre>
    </div>
    
    Rest API：
    <div id="code" class="highlight">
        <pre class="prettyprint">
            ${restApi}<br/>
        </pre>
    </div>
    
    <c:if test="${springConfig != null}">
    	Spring Config Demo：
	    <div id="springConfig" class="highlight">
	        <pre class="prettyprint">
	        <c:forEach var="line" items="${springConfig}">
	            ${line}<br/>
	        </c:forEach>
	        </pre>
	    </div>
    </c:if>
    
</div>
<script>
    prettyPrint();
</script>

open-monitor-center/cachecloud/cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appList.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" import="com.sohu.cache.web.enums.AppOrderByEnum" %>
<%@ include file="/WEB-INF/jsp/manage/commons/appConstants.jsp"%>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>CacheCloud应用列表</title>
    <jsp:include page="/WEB-INF/include/head.jsp"/>
    <script type="text/javascript">
  	//改变内存阀值
    function cleanAppData(appId){
    	var appCleanDataBtn = document.getElementById("appCleanDataBtn" + appId);
    	appCleanDataBtn.disabled = true;
    	
    	$.post(
    		'/admin/app/cleanAppData.do',
    		{
    			appId: appId
    		},
            function(data){
                if(data==1){
                    alert("appId:" + appId + "清除数据成功！");
                }else{
                    alert("appId:" + appId + "清除数据失败,请联系管理员查看原因！");
                }
            	appCleanDataBtn.disabled = false;
            }
         );
    }
    </script>
</head>
<body role="document">
<div class="container">
    <jsp:include page="/WEB-INF/include/headMenu.jsp"/>
    <div id="systemAlert">
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="page-header">
                <h4>全局信息</h4>
            </div>
            <table class="table table-striped table-hover">
                <tbody>
                <tr>
                    <td>总应用数</td>
                    <td>${totalApps}个 </td>
                    <td>总申请内存</td>
                    <td>
                    	<fmt:formatNumber value="${totalApplyMem / 1024.0}" pattern="0.00"/>G
                    </td>
                </tr>
                <tr>
                    <td>已使用内存</td>
                    <td>
                    	<fmt:formatNumber value="${totalUsedMem / 1024.0}" pattern="0.00"/>G
                    </td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div class="page-header">
                <h4>联系我们: </h4>
            </div>
            <div id="contact" class="page-body">
            	<jsp:include page="/WEB-INF/include/contact.jsp"/>
            </div>
        </div>
    </div>
    
    
    
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h4>应用列表</h4>
            </div>
            <c:if test="${currentUser.type == 0}">
				<div style="float:right">
					<form class="form-inline" method="post" action="/admin/app/list.do" id="appList" name="ec">
					  <div class="form-group">
					    <input type="text" class="form-control" id="appId" name="appId" value="${appSearch.appId}" placeholder="应用ID" onchange="testisNum(this.id)">
					  </div>
					  <div class="form-group">
					    <input type="text" class="form-control" id="appName" name="appName" value="${appSearch.appName}" placeholder="应用名">
					  </div>
					  <div class="form-group">
						<select name="appType" class="form-control">
							<option value="">
								全部类型
							</option>
							<option value="2" <c:if test="${appSearch.appType == 2}">selected</c:if>>
								Redis-cluster
							</option>
							<option value="5" <c:if test="${appSearch.appType == 5}">selected</c:if>>
								redis-sentinel
							</option>
							<option value="6" <c:if test="${appSearch.appType == 6}">selected</c:if>>
								redis-standalone
							</option>
						</select>
					 </div>
					 <div class="form-group">
						<select name="appStatus" class="form-control">
							<option value="-1">
								全部状态
							</option>
							<option value="0" <c:if test="${appSearch.appStatus == 0}">selected</c:if>>
								未分配
							</option>
							<option value="1" <c:if test="${appSearch.appStatus == 1}">selected</c:if>>
								申请中
							</option>
							<option value="2" <c:if test="${appSearch.appStatus == 2}">selected</c:if>>
								运行中
							</option>
		                    <option value="3" <c:if test="${appSearch.appStatus == 3}">selected</c:if>>
		                       	 已下线
		                    </option>
		                    <option value="4" <c:if test="${appSearch.appStatus == 4}">selected</c:if>>
		                       	 驳回
		                    </option>
						</select>
					 </div>
					 <div class="form-group">
						<select name="importantLevel" class="form-control">
							<option value="">
								全部级别
							</option>
							<option value="1" <c:if test="${appSearch.importantLevel == 1}">selected</c:if>>
								S级
							</option>
							<option value="2" <c:if test="${appSearch.importantLevel == 2}">selected</c:if>>
								A级
							</option>
							<option value="3" <c:if test="${appSearch.importantLevel == 3}">selected</c:if>>
								B级
							</option>
		                    <option value="4" <c:if test="${appSearch.importantLevel == 4}">selected</c:if>>
		                       	C级
		                    </option>
						</select>
					 </div>
					 
					 <div class="form-group">
						<select name="pageSize" class="form-control">
							<option value="10" <c:if test="${page.pageSize == 10}">selected</c:if>>
								10行
							</option>
		                    <option value="20" <c:if test="${page.pageSize == 20}">selected</c:if>>
		                       	 20行
		                    </option>
		                    <option value="50" <c:if test="${page.pageSize == 50}">selected</c:if>>
		                       	 50行
		                    </option>
		                    <option value="100" <c:if test="${page.pageSize == 100}">selected</c:if>>
		                       	 100行
		                    </option>
						</select>
					 </div>
					 
					 
					  <input type="hidden" name="pageNo" id="pageNo">
					  <button type="submit" class="btn btn-default">查询</button>
					</form>
				</div>
		    </c:if>
		</div>
	</div>
	<div class="row">
			<br/>
			<div class="col-md-12">
	            <table class="table table-striped table-hover" style="margin-top: 0px">
	                <thead>
		                <tr>
		                    <td>应用ID</td>
		                    <td>应用名</td>
		                    <td>应用类型</td>
		                    <td>内存详情</td>
		                    <td>命中率</td>
		                    <td>已运行时间</td>
		                    <td>申请状态</td>
		                    <td>操作</td>
		                </tr>
	                </thead>
	                <tbody>
	                	<c:forEach items="${appDetailList}" var="appDetail">
	                		 <tr>
			                    <td>
			                    	<c:choose>
			                    		<c:when test="${appDetail.appDesc.status == 0 or appDetail.appDesc.status == 1}">
			                   				${appDetail.appDesc.appId}
			                    		</c:when>
			                    		<c:when test="${appDetail.appDesc.status == 2 or appDetail.appDesc.status == 3 or appDetail.appDesc.status == 4}">
			                    			<a title="${appDetail.appDesc.intro}" target="_blank" href="/admin/app/index.do?appId=${appDetail.appDesc.appId}">${appDetail.appDesc.appId}</a>
			                    		</c:when>
			                    	</c:choose>
			                    </td>
			                    <td>
			                    	<c:choose>
			                    		<c:when test="${appDetail.appDesc.status == 0 or appDetail.appDesc.status == 1}">
			                    			${appDetail.appDesc.name}
			                    		</c:when>
			                    		<c:when test="${appDetail.appDesc.status == 2 or appDetail.appDesc.status == 3 or appDetail.appDesc.status == 4}">
			                    			<a target="_blank" href="/admin/app/index.do?appId=${appDetail.appDesc.appId}">${appDetail.appDesc.name}</a>
			                    		</c:when>
			                    	</c:choose>
			                    </td>
			                    <td>
			                    	<c:choose>
			        		            <c:when test="${appDetail.appDesc.type == 2}">redis-cluster</c:when>
	    		        		        <c:when test="${appDetail.appDesc.type == 5}">redis-sentinel</c:when>
	    		        		        <c:when test="${appDetail.appDesc.type == 6}">redis-standalone</c:when>
			                    	</c:choose>
			                    </td>
			                    <td>
			                        <div class="progress margin-custom-bottom0">
			                        	<c:choose>
			                        		<c:when test="${appDetail.memUsePercent >= 80}">
												<c:set var="progressBarStatus" value="progress-bar-danger"/>
			                        		</c:when>
			                        		<c:otherwise>
												<c:set var="progressBarStatus" value="progress-bar-success"/>
			                        		</c:otherwise>
			                        	</c:choose>
										<div class="progress-bar ${progressBarStatus}"
											role="progressbar" aria-valuenow="${appDetail.memUsePercent}" aria-valuemax="100"
											aria-valuemin="0" style="width: ${appDetail.memUsePercent}%">
											<label style="color: #000000">
												<fmt:formatNumber value="${appDetail.mem * appDetail.memUsePercent / 100 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Used/<fmt:formatNumber value="${appDetail.mem / 1024 * 1.0}" pattern="0.00"/>G&nbsp;&nbsp;Total
											</label>
										</div>
									</div>
			                    </td>
			                    <td>
			                    	<c:choose>
			                    		<c:when test="${appDetail.hitPercent <= 0}">
			                    			无
			                    		</c:when>
			                    		<c:when test="${appDetail.hitPercent <= 30}">
			                    			<label class="label label-danger">${appDetail.hitPercent}%</label>
			                    		</c:when>
			                    		<c:when test="${appDetail.hitPercent >= 30 && appDetail.hitPercent < 50}">
			                    			<label class="label label-warning">${appDetail.hitPercent}%</label>
			                    		</c:when>
			                    		<c:when test="${appDetail.hitPercent >= 50 && appDetail.hitPercent < 90}">
			                    			<label class="label label-info">${appDetail.hitPercent}%</label>
			                    		</c:when>
			                    		<c:otherwise>
			                    			<label class="label label-success">${appDetail.hitPercent}%</label>
			                    		</c:otherwise>
			                    	</c:choose>
			                    	
			                    </td>
			                    <td>${appDetail.appDesc.appRunDays}天</td>
			                    <td>
			                    	<c:choose>
			                    		<c:when test="${appDetail.appDesc.status == 0}">
			                    			<font color="red">未申请</font>
			                    		</c:when>
			                    		<c:when test="${appDetail.appDesc.status == 1}">
			                    			<font color="red">申请中</font>
			                    		</c:when>
			                    		<c:when test="${appDetail.appDesc.status == 2}">
			                    			运行中
			                    		</c:when>
	                                    <c:when test="${appDetail.appDesc.status == 3}">
	                                        <font color="red">已下线</font>
	                                    </c:when>
	                                    <c:when test="${appDetail.appDesc.status == 4}">
	                                        <font color="red">驳回</font>
	                                    </c:when>
			                    	</c:choose>
			                    </td>
			                    <td>
			                    	<c:choose>
			                    		<c:when test="${appDetail.appDesc.status == 2 && appDetail.appDesc.isTest == 1}">
			                    			<button type="button" id="appCleanDataBtn${appDetail.appDesc.appId}" onclick="if(window.confirm('确认要清除应用appid=${appDetail.appDesc.appId}的数据?!')){cleanAppData('${appDetail.appDesc.appId}');return true;}else{return false;}">清空数据</button>
			                    		</c:when>
			                    	</c:choose>
			                    </td>
			                </tr>
	                	</c:forEach>
	                </tbody>
	            </table>
            </div>
            <div style="margin-bottom: 10px;float: right;margin-right: 15px">
				<span>
					<ul id='ccPagenitor' style="margin-bottom: 0px;margin-top: 0px"></ul>
					<div id="pageDetail" style="float:right;padding-top:7px;padding-left:8px;color:#4A64A4;display: none">共${page.totalPages}页,${page.totalCount}条</div>		
				</span>
			</div>
        </div>
    </div>

<jsp:include page="/WEB-INF/include/foot.jsp"/>

<script type="text/javascript" src="/resources/js/mem-cloud.js"></script>

<script src="/resources/bootstrap/paginator/bootstrap-paginator.js"></script>
<script src="/resources/bootstrap/paginator/custom-pagenitor.js"></script>
<script type="text/javascript">
    $(function(){
    	var userType = '${currentUser.type}';
    	if (userType == 0) {
    		//分页点击函数
        	var pageClickedFunc = function (e, originalEvent, type, page){
        		//form传参用pageSize
        		document.getElementById("pageNo").value=page;
        		document.getElementById("appList").submit();
        	};
        	//分页组件
            var element = $('#ccPagenitor');
            //当前page号码
            var pageNo = '${page.pageNo}';
            //总页数
            var totalPages = '${page.totalPages}';
            //显示总页数
            var numberOfPages = '${page.numberOfPages}';
    		var options = generatePagenitorOption(pageNo, numberOfPages, totalPages, pageClickedFunc);
    		if(totalPages > 0){
    			element.bootstrapPaginator(options);
    			document.getElementById("pageDetail").style.display = "";
    		}else{
    			element.html("未查询到相关记录！");
    		}
    	}
    	
    });
</script>


</body>
</html>