open-monitor-center/cachecloud/cachecloud-open-web/src/main/java/com/sohu/cache/entity/InstanceFault.java
package com.sohu.cache.entity;

import java.io.Serializable;
import java.util.Date;

public class InstanceFault implements Serializable {

    private static final long serialVersionUID = 8141174905675892249L;

    private int id;

    private int appId;

    private int instId;

    private String ip;

    private int port;

    private int status;

    private int type;

    private Date createTime;

    private String reason;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getAppId() {
        return appId;
    }

    public void setAppId(int appId) {
        this.appId = appId;
    }

    public int getInstId() {
        return instId;
    }

    public void setInstId(int instId) {
        this.instId = instId;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getTypeDesc() {
        InstanceInfo info = new InstanceInfo();
        info.setType(type);
        return info.getTypeDesc();
    }

    public String getStatusDesc() {
        InstanceInfo info = new InstanceInfo();
        info.setStatus(this.status);
        return info.getStatusDesc();
    }

}

open-monitor-center/cachecloud/cachecloud-open-web/src/main/java/com/sohu/cache/entity/InstanceStats.java
package com.sohu.cache.entity;

import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.Map;

/**
 * 实例的简化的统计信息
 *
 * User: lingguo
 * Date: 14-7-27 下午3:59
 */
public class InstanceStats {
    /* id */
    private long id;

    /* 实例id */
    private long instId;

    /* app id */
    private long appId;

    /* host id */
    private long hostId;

    /* ip地址 */
    private String ip;

    /* port */
    private int port;

    /* 主从，1主2从 */
    private byte role;

    /* 启用实例时设置的内存，单位：byte */
    private long maxMemory;

    /* 实例当前已用的内存，单位：byte */
    private long usedMemory;

    /*
     * 实例内存使用率
     */
    private double memUsePercent;

    /* 当前的item数 */
    private long currItems;

    /* 当前的连接数 */
    private int currConnections;

    /* 未命中数*/
    private long misses;

    /* 命中数 */
    private long hits;

    /* 开始收集时间 */
    private Timestamp createTime;

    /* 最后更新时间 */
    private Timestamp modifyTime;
    
    /**
     * 内存碎片率
     */
    private double memFragmentationRatio;
    
    /**
     * aof阻塞次数
     */
    private int aofDelayedFsync;

    private boolean isRun;

    /**
     * 实例相关全部统计指标
     */
    private Map<String,Object> infoMap;

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public long getMaxMemory() {
        return maxMemory;
    }

    public void setMaxMemory(long maxMemory) {
        this.maxMemory = maxMemory;
    }

    public long getUsedMemory() {
        return usedMemory;
    }

    public void setUsedMemory(long usedMemory) {
        this.usedMemory = usedMemory;
    }

    public long getCurrItems() {
        return currItems;
    }

    public void setCurrItems(long currItems) {
        this.currItems = currItems;
    }

    public int getCurrConnections() {
        return currConnections;
    }

    public void setCurrConnections(int currConnections) {
        this.currConnections = currConnections;
    }


    public long getMisses() {
        return misses;
    }

    public void setMisses(long misses) {
        this.misses = misses;
    }

    public long getHits() {
        return hits;
    }

    public void setHits(long hits) {
        this.hits = hits;
    }

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public long getHostId() {
        return hostId;
    }

    public void setHostId(long hostId) {
        this.hostId = hostId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    public byte getRole() {
        return role;
    }

    public void setRole(byte role) {
        this.role = role;
    }

    public long getInstId() {
        return instId;
    }

    public void setInstId(long instId) {
        this.instId = instId;
    }

    public double getMemFragmentationRatio() {
        return memFragmentationRatio;
    }

    public void setMemFragmentationRatio(double memFragmentationRatio) {
        this.memFragmentationRatio = memFragmentationRatio;
    }

    public int getAofDelayedFsync() {
        return aofDelayedFsync;
    }

    public void setAofDelayedFsync(int aofDelayedFsync) {
        this.aofDelayedFsync = aofDelayedFsync;
    }

    @Override
    public String toString() {
        return "InstanceStats [id=" + id + ", instId=" + instId + ", appId=" + appId + ", hostId=" + hostId + ", ip="
                + ip + ", port=" + port + ", role=" + role + ", maxMemory=" + maxMemory + ", usedMemory=" + usedMemory
                + ", memUsePercent=" + memUsePercent + ", currItems=" + currItems + ", currConnections="
                + currConnections + ", misses=" + misses + ", hits=" + hits + ", createTime=" + createTime
                + ", modifyTime=" + modifyTime + ", memFragmentationRatio=" + memFragmentationRatio
                + ", aofDelayedFsync=" + aofDelayedFsync + ", isRun=" + isRun + ", infoMap=" + infoMap + "]";
    }

    public Map<String, Object> getInfoMap() {
        return infoMap;
    }

    public void setInfoMap(Map<String, Object> infoMap) {
        this.infoMap = infoMap;
    }

    public boolean isRun() {
        return isRun;
    }

    public void setRun(boolean isRun) {
        this.isRun = isRun;
    }

    public double getMemUsePercent() {
        if(maxMemory<=0){
            return 0.0D;
        }
        double percent = 100 * (double) usedMemory / (maxMemory);
        DecimalFormat df = new DecimalFormat("##.##");
        return Double.parseDouble(df.format(percent));
    }
    
    /**
     * 命中率
     * @return
     */
    public String getHitPercent(){
		long totalHits = hits + misses;
		if (totalHits <= 0) {
			return "无命令执行";
		}
		double percent = 100 * (double) hits / totalHits;
		DecimalFormat df = new DecimalFormat("##.##");
		return df.format(percent) + "%";
    }
}

open-monitor-center/cachecloud/cachecloud-open-web/src/main/java/com/sohu/cache/web/controller/InstanceController.java
package com.sohu.cache.web.controller;

import com.sohu.cache.alert.InstanceAlertService;
import com.sohu.cache.entity.*;
import com.sohu.cache.redis.RedisCenter;
import com.sohu.cache.stats.app.AppStatsCenter;
import com.sohu.cache.stats.instance.InstanceStatsCenter;
import com.sohu.cache.util.ConstUtils;
import com.sohu.cache.web.vo.RedisSlowLog;
import com.sohu.cache.web.chart.key.ChartKeysUtil;
import com.sohu.cache.web.chart.model.SplineChartEntity;
import com.sohu.cache.web.util.DateUtil;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.math.NumberUtils;
import org.apache.commons.lang.time.DateUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.ModelAndView;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.text.ParseException;
import java.util.*;

/**
 * Created by hym on 14-7-27.
 */
@Controller
@RequestMapping("/admin/instance")
public class InstanceController {
    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    @Resource(name = "instanceStatsCenter")
    private InstanceStatsCenter instanceStatsCenter;

    @Resource(name = "appStatsCenter")
    private AppStatsCenter appStatsCenter;

    @Resource(name = "redisCenter")
    private RedisCenter redisCenter;

    @Resource
    private InstanceAlertService instanceAlertService;

    @RequestMapping("/index")
    public ModelAndView index(HttpServletRequest request, HttpServletResponse response, Model model, Integer admin, Long instanceId, Long appId, String tabTag) {

        String startDateParam = request.getParameter("startDate");
        String endDateParam = request.getParameter("endDate");

        if (StringUtils.isBlank(startDateParam) || StringUtils.isBlank(endDateParam)) {
            Date endDate = new Date();
            Date startDate = DateUtils.addDays(endDate, -1);
            startDateParam = DateUtil.formatDate(startDate, "yyyyMMdd");
            endDateParam = DateUtil.formatDate(endDate, "yyyyMMdd");
        }
        model.addAttribute("startDate", startDateParam);
        model.addAttribute("endDate", endDateParam);

        if (instanceId != null && instanceId > 0) {
            model.addAttribute("instanceId", instanceId);
            InstanceInfo instanceInfo = instanceStatsCenter.getInstanceInfo(instanceId);

            if (instanceInfo == null) {
                model.addAttribute("type", -1);
            } else {
                if (appId != null && appId > 0) {
                    model.addAttribute("appId", appId);
                } else {
                    model.addAttribute("appId", instanceInfo.getAppId());
                }
                model.addAttribute("type", instanceInfo.getType());
            }
        } else {

        }
        if (tabTag != null) {
            model.addAttribute("tabTag", tabTag);
        }
        return new ModelAndView("instance/instanceIndex");
    }

    @RequestMapping("/stat")
    public ModelAndView stat(HttpServletRequest request, HttpServletResponse response, Model model, Integer admin, Long instanceId) {

        String startDateParam = request.getParameter("startDate");
        String endDateParam = request.getParameter("endDate");

        if (StringUtils.isBlank(startDateParam) || StringUtils.isBlank(endDateParam)) {
            Date endDate = new Date();
            Date startDate = DateUtils.addDays(endDate, -1);
            startDateParam = DateUtil.formatDate(startDate, "yyyyMMdd");
            endDateParam = DateUtil.formatDate(endDate, "yyyyMMdd");
        }
        model.addAttribute("startDate", startDateParam);
        model.addAttribute("endDate", endDateParam);

        if (instanceId != null && instanceId > 0) {
            model.addAttribute("instanceId", instanceId);
            InstanceInfo instanceInfo = instanceStatsCenter.getInstanceInfo(instanceId);
            model.addAttribute("instanceInfo", instanceInfo);
            model.addAttribute("appId", instanceInfo.getAppId());
            model.addAttribute("appDetail", appStatsCenter.getAppDetail(instanceInfo.getAppId()));
            InstanceStats instanceStats = instanceStatsCenter.getInstanceStats(instanceId);
            model.addAttribute("instanceStats", instanceStats);
            List<AppCommandStats> topLimitAppCommandStatsList = appStatsCenter.getTopLimitAppCommandStatsList(instanceInfo.getAppId(), Long.parseLong(startDateParam) * 10000, Long.parseLong(endDateParam) * 10000, 5);
            model.addAttribute("appCommandStats", topLimitAppCommandStatsList);
        }
        return new ModelAndView("instance/instanceStat");
    }

    @RequestMapping("/advancedAnalysis")
    public ModelAndView advancedAnalysis(HttpServletRequest request, HttpServletResponse response, Model model, Integer admin, Long instanceId) {

        String startDateParam = request.getParameter("startDate");
        String endDateParam = request.getParameter("endDate");

        if (StringUtils.isBlank(startDateParam) || StringUtils.isBlank(endDateParam)) {
            Date endDate = new Date();
            Date startDate = DateUtils.addDays(endDate, -1);
            startDateParam = DateUtil.formatDate(startDate, "yyyyMMdd");
            endDateParam = DateUtil.formatDate(endDate, "yyyyMMdd");
        }
        model.addAttribute("startDate", startDateParam);
        model.addAttribute("endDate", endDateParam);

        if (instanceId != null && instanceId > 0) {
            model.addAttribute("instanceId", instanceId);
            InstanceInfo instanceInfo = instanceStatsCenter.getInstanceInfo(instanceId);
            model.addAttribute("instanceInfo", instanceInfo);
            model.addAttribute("appId", instanceInfo.getAppId());
            List<AppCommandStats> topLimitAppCommandStatsList = appStatsCenter.getTopLimitAppCommandStatsList(instanceInfo.getAppId(), Long.parseLong(startDateParam) * 10000, Long.parseLong(endDateParam) * 10000, 5);
            model.addAttribute("appCommandStats", topLimitAppCommandStatsList);
        } else {

        }
        return new ModelAndView("instance/instanceAdvancedAnalysis");
    }

    /**
     * 获取某个命令时间分布图
     *
     * @param instanceId  实例id
     * @param commandName 命令名称
     * @throws java.text.ParseException
     */
    @RequestMapping("/getCommandStats")
    public ModelAndView getCommandStats(HttpServletRequest request,
                                        HttpServletResponse response, Model model, Long instanceId,
                                        String commandName) throws ParseException {
        String startDateParam = request.getParameter("startDate");
        String endDateParam = request.getParameter("endDate");

        if (StringUtils.isBlank(startDateParam) || StringUtils.isBlank(endDateParam)) {
            Date endDate = new Date();
            Date startDate = DateUtils.addDays(endDate, -1);
            startDateParam = DateUtil.formatDate(startDate, "yyyyMMdd");
            endDateParam = DateUtil.formatDate(endDate, "yyyyMMdd");
        }
        model.addAttribute("startDate", startDateParam);
        model.addAttribute("endDate", endDateParam);

        Date startDate = DateUtil.parseYYYYMMdd(startDateParam);
        Date endDate = DateUtil.parseYYYYMMdd(endDateParam);
        if (instanceId != null) {
            long firstDayBegin = NumberUtils.toLong(DateUtil.formatYYYYMMdd(startDate) + "0000");
            long firstDayEnd = NumberUtils.toLong(DateUtil.formatYYYYMMdd(startDate) + "2359");
            long secondDayBegin = NumberUtils.toLong(DateUtil.formatYYYYMMdd(endDate) + "0000");
            long secondDayEnd = NumberUtils.toLong(DateUtil.formatYYYYMMdd(endDate) + "2359");
            long bt = System.currentTimeMillis();
            List<InstanceCommandStats> instanceCommandStatsListFirst = instanceStatsCenter
                    .getCommandStatsList(instanceId, firstDayBegin, firstDayEnd, commandName);
            List<InstanceCommandStats> instanceCommandStatsListSecond = instanceStatsCenter
                    .getCommandStatsList(instanceId, secondDayBegin, secondDayEnd, commandName);
            long et = System.currentTimeMillis() - bt;
            Map<String, InstanceCommandStats> cmdStatsFirst = new HashMap<String, InstanceCommandStats>();
            Map<String, InstanceCommandStats> cmdStatsSecond = new HashMap<String, InstanceCommandStats>();

            for (InstanceCommandStats first : instanceCommandStatsListFirst) {
                cmdStatsFirst.put(first.getCollectTime() + "", first);
            }
            for (InstanceCommandStats second : instanceCommandStatsListSecond) {
                cmdStatsSecond.put(second.getCollectTime() + "", second);
            }

            SplineChartEntity splineChartEntity = new SplineChartEntity();
            String container = request.getParameter("container");
            if (container != null) {
                splineChartEntity.renderTo(container);
            }
            model.addAttribute("chart", splineChartEntity);
            splineChartEntity.putTitle(ChartKeysUtil.TitleKey.TEXT.getKey(), "命令:" + commandName + " 的比较曲线【" + startDateParam + "】-【" + endDateParam + "】");
            splineChartEntity.setYAxisTitle("y");
            List<Long> data1 = new ArrayList<Long>();
            List<Long> data2 = new ArrayList<Long>();
            Map<String, Object> serie1 = new HashMap<String, Object>();
            serie1.put("name", startDateParam);
            serie1.put("data", data1);
//            serie1.put("type", "area");
            Map<String, Object> serie2 = new HashMap<String, Object>();
            serie2.put("name", endDateParam);
            serie2.put("data", data2);
//            serie2.put("type", "area");

open-monitor-center/cachecloud/cachecloud-open-web/src/main/webapp/WEB-INF/jsp/instance/instanceClientList.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<div class="container">
<br/>
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h4>当前客户端连接信息</h4>
        </div>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <td>连接信息</td>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${clientList}" var="clientInfo" varStatus="status">
                <tr>
                    <td>${clientInfo}</td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>
</div>

open-monitor-center/cachecloud/cachecloud-open-web/src/main/webapp/WEB-INF/jsp/instance/instanceFault.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>
<div class="row">
    <div class="col-md-12 page-header">
    	实例故障情况
    </div>
    <div style="margin-top: 20px">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <td>应用ID</td>
                <td>实例ip:port</td>
                <td>实例状态</td>
                <td>类型</td>
                <td>触发时间</td>
            </tr>
            </thead>
            <tbody>
            <c:forEach var="instance" items="${list}" varStatus="status">
                <tr>
                    <td>
                        <a href="/admin/app/index.do?appId=${instance.appId}" target="_blank">${instance.appId}</a>
                    </td>
                    <td>
                        <a href="/admin/instance/index.do?instanceId=${instance.instId}" target="_blank">${instance.ip}:${instance.port}</a>
                    </td>
                    <td>${instance.statusDesc}</td>
                    <td>${instance.typeDesc}</td>
                    <td><fmt:formatDate value="${instance.createTime}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>

open-monitor-center/cachecloud/cachecloud-open-web/src/main/webapp/WEB-INF/jsp/instance/instanceStat.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<div class="container">
    <br/>

    <div class="row">
        <div class="col-md-8">
            <div class="page-header">
                <h4>实例信息-所属应用<a href="/admin/app/index.do?appId=${appDetail.appDesc.appId}" target="_blank">【${appDetail.appDesc.name}】</a></h4>
            </div>
            <table class="table table-striped table-hover">
                <tbody>
                <tr>
                    <td>内存使用率</td>
                    <td>
                        <div class="progress margin-custom-bottom0">
                            <c:choose>
                            <c:when test="${instanceStats.memUsePercent >= 80}">
                            <div class="progress-bar progress-bar-danger"
                                 role="progressbar" aria-valuenow="${instanceStats.memUsePercent}" aria-valuemax="100"
                                 aria-valuemin="0" style="width: ${instanceStats.memUsePercent}%">
                                </c:when>
                                <c:otherwise>
                                <div class="progress-bar progress-bar-success"
                                     role="progressbar" aria-valuenow="${instanceStats.memUsePercent}" aria-valuemax="100"
                                     aria-valuemin="0" style="width: ${instanceStats.memUsePercent}%">				                    		</c:otherwise>
                                    </c:choose>
                                    <label style="color: #000000">
                                        <fmt:formatNumber value="${instanceInfo.mem  * instanceStats.memUsePercent / 100 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Used/${instanceInfo.mem / 1024 * 1.0}G&nbsp;&nbsp;Total
                                    </label>
                                </div>
                            </div>
                    </td>
                    <!--
                     <td>${instanceInfo.mem}M</td>
                     <td>已用内存TODO</td>
                     <td><fmt:formatNumber value="${instanceStats.usedMemory/1024/1024}" pattern="#,#00"/>M</td>
                     -->
                    <td>命中率</td>
                    <c:choose>
                        <c:when test="${instanceStats.misses+instanceStats.hits==0}">
                            <td>无操作数据</td>
                        </c:when>
                        <c:otherwise>
                            <td><fmt:formatNumber value="${instanceStats.hits/(instanceStats.misses+instanceStats.hits)}" type="percent" maxFractionDigits="2"></fmt:formatNumber></td>
                        </c:otherwise>
                    </c:choose>

                    <td>实例角色</td>
                    <td>
                        <c:if test="${instanceStats.role == 1}">master</c:if>
                        <c:if test="${instanceStats.role == 2}">slave</c:if>
                    </td>
                </tr>
                <tr>
                    <td>当前对象数</td>
                    <td><fmt:formatNumber value="${instanceStats.currItems}" pattern="#,#00"/></td>
                    <td>实例类型</td>
                    <td>${instanceInfo.typeDesc}</td>
                    <td>当前连接数</td>
                    <td>${instanceStats.currConnections}</td>
                </tr>
                <tr>
                    <td>实例地址</td>
                    <td>${instanceInfo.ip}:${instanceInfo.port}</td>
                    <td>运行状态</td>
                    <td>${instanceInfo.statusDesc}</td>
                    <td>运行天数</td>
                    <td>
                    <c:choose>
                        <c:when test="${instanceInfo.type == 1}">
                            <fmt:formatNumber value="${instanceStats.infoMap['stats'].uptime/60/60/24}" pattern="0.0"/>
                        </c:when>
                        <c:otherwise>${instanceStats.infoMap['Server'].uptime_in_days}</c:otherwise>
                    </c:choose>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <div class="page-header">
                <h4>联系我们:</h4>
            </div>
            <div id="contact" class="page-body">
                 <jsp:include page="/WEB-INF/include/contact.jsp"/>
            </div>
        </div>
    </div>
    <div class="row">
        <c:choose>
            <c:when test="${instanceInfo.type == 1}">
                <div class="page-header">
                    <h4>实时状态</h4>
                </div>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <td>分组</td>
                        <td>键值</td>
                        <td>值</td>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${instanceStats.infoMap['stats']}" var="info" varStatus="status">
                        <c:if test="${status.last}">
                            <c:set var="rows" value="${status.count}" scope="page"></c:set>
                        </c:if>
                    </c:forEach>
                    <c:forEach items="${instanceStats.infoMap['stats']}" var="info" varStatus="status">
                        <tr>
                            <c:if test="${status.first}">
                                <td rowspan="${rows}">stats</td>
                            </c:if>
                            <td>${info.key}</td>
                            <td>${info.value}</td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>

                <div class="page-header">
                    <h4>实例的item状态</h4>
                </div>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <td>item号</td>
                        <td>evicted_nonzero</td>
                        <td>outofmemory</td>
                        <td>reclaimed</td>
                        <td>age</td>
                        <td>evicted_time</td>
                        <td>number</td>
                        <td>tailrepairs</td>
                        <td>evicted</td>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${instanceStats.infoMap['itemsVo']}" var="item" varStatus="status">
                        <tr>
                            <td>${item.key}</td>
                            <td>${item.value.evictedNonzero}</td>
                            <td>${item.value.outOfMemory}</td>
                            <td>${item.value.reclaimed}</td>
                            <td>${item.value.age}</td>
                            <td>${item.value.evictedTime}</td>
                            <td>${item.value.number}</td>
                            <td>${item.value.tailRepairs}</td>
                            <td>${item.value.evicted}</td>
                        </tr>
                    </c:forEach>
                    </tbody>
                </table>

                <div class="page-header">
                    <h4>实例的slab状态</h4>
                </div>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <td>slab号</td>
                        <td>free_<br/>chunks</td>
                        <td>incr_hits</td>
                        <td>delete_hits</td>
                        <td>cmd_set</td>
                        <td>get_hits</td>
                        <td>chunk_size</td>
                        <td>decr_hits</td>
                        <td>chunks_<br/>per_page</td>
                        <td>free_chunks_end</td>
                        <td>used_<br/>chunks</td>
                        <td>total_pages</td>
                        <%--<td>cas_hits</td>--%>
                        <td>mem_requested</td>
                        <%--<td>cas_badval</td>--%>
                        <td>total_<br/>chunks</td>

                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${instanceStats.infoMap['slabsVo']}" var="slab" varStatus="status">
                        <tr>
                            <td>${slab.key}</td>
                            <td>${slab.value.freeChunks}</td>
                            <td>${slab.value.incrHits}</td>
                            <td>${slab.value.deleteHits}</td>
                            <td>${slab.value.cmdSet}</td>
                            <td>${slab.value.getHits}</td>
                            <td>${slab.value.chunkSize}</td>
                            <td>${slab.value.decrHits}</td>
                            <td>${slab.value.chunksPerPage}</td>
                            <td>${slab.value.freeChunksEnd}</td>
                            <td>${slab.value.usedChunks}</td>
                            <td>${slab.value.totalPages}</td>
                            <%--<td>${slab.value.casHits}</td>--%>
                            <td>${slab.value.memRequested}</td>
                            <%--<td>${slab.value.casBadval}</td>--%>
                            <td>${slab.value.totalChunks}</td>

                        </tr>
                    </c:forEach>
                    </tbody>
                </table>
            </c:when>
            <c:when test="${instanceInfo.type == 2 or instanceInfo.type == 5 or instanceInfo.type == 6}">
                <div class="page-header">
                    <h4>实时状态</h4>
                </div>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                    <tr>
                        <td>分组</td>
                        <td>键值</td>
                        <td>值</td>
                    </tr>
                    </thead>
                    <tbody>
                    <c:forEach items="${instanceStats.infoMap}" var="infoMap">
                        <c:forEach items="${infoMap.value}" var="info" varStatus="status">
                            <c:if test="${status.last}">
                                <c:set var="rows" value="${status.count}" scope="page"></c:set>
                            </c:if>
                        </c:forEach>
                        <c:forEach items="${infoMap.value}" var="info" varStatus="status">
                            <tr>
                                <c:if test="${status.first}">
                                    <td rowspan="${rows}">${infoMap.key}</td>
                                </c:if>
                                <td>${info.key}</td>
                                <td>${info.value}</td>
                            </tr>
                        </c:forEach>
                    </c:forEach>
                    </tbody>
                </table>
            </c:when>
        </c:choose>
    </div>
</div>